import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Client Notes",
  description: "Generated by Quick Client Notes & Reports",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation/>
        <main>
          {children}
        </main>
        
      </body>
    </html>
  );
}
